
---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /audiobooks:/audiobooks
      - /podcasts:/podcasts
      - /config:/config
      - /metadata>:/metadata
    environment:
      - TZ=America/New_York
