---
- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: custom
    url: # whoogle # google, duckduckgo, bing, baidu, brave or custom
    focus: true
    target: _blank # One of _self, _blank, _parent or _top

- openweathermap:
    latitude: {{long}}
    longitude: {{lat}}
    units: imperial # or imperial
    provider: openweathermap
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 0

- datetime:
    text_size: m
    format:
        timeStyle: short
        hourCycle: h12